### ISSUE TITLE
2.2.2 Breaking changes 

### ISSUE THREAD

**Issue by andreijs** [rexxars/commonmark-react-renderer#8]
Hey, this no longers work in my project worked a few days ago ... now breaking

```
error given was: Error: Unknown node type "Header"
[1]     at Object.renderNodes [as render] (/Users/amiulescu/househunt/housemeerkat/node_modules/react-markdown/node_modules/commonmark-react-renderer/src/commonmark-react-renderer.js:211:23)
[1]     at [object Object].React.createClass.render (/Users/amiulescu/househunt/housemeerkat/node_modules/react-markdown/src/react-markdown.js:43:34)
[1]     at [object Object].ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext (/Users/amiulescu/househunt/housemeerkat/node_modules/react/lib/ReactCompositeComponent.js:587:34)
[1]     at [object Object].ReactCompositeComponentMixin._renderValidatedComponent (/Users/amiulescu/househunt/housemeerkat/node_modules/react/lib/ReactCompositeComponent.js:607:32)
[1]     at [object Object].wrapper [as _renderValidatedComponent] (/Users/amiulescu/househunt/housemeerkat/node_modules/react/lib/ReactPerf.js:66:21)
[1]     at [object Object].ReactCompositeComponentMixin.mountComponent (/Users/amiulescu/househunt/housemeerkat/node_modules/react/lib/ReactCompositeComponent.js:220:30)
[1]     at [object Object].wrapper [as mountComponent] (/Users/amiulescu/househunt/housemeerkat/node_modules/react/lib/ReactPerf.js:66:21)
[1]     at Object.ReactReconciler.mountComponent (/Users/amiulescu/househunt/housemeerkat/node_modules/react/lib/ReactReconciler.js:37:35)
[1]     at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (/Users/amiulescu/househunt/housemeerkat/node_modules/react/lib/ReactMultiChild.js:241:44)
[1]     at ReactDOMComponent.Mixin._createContentMarkup (/Users/amiulescu/househunt/housemeerkat/node_modules/react/lib/ReactDOMComponent.js:591:32)
```

**Comment by mooncakelmn** [comment]
:+1:  for the same issue.

I'm using `react-markdown` and created an issue for it https://github.com/rexxars/react-markdown/issues/13

**Comment by rexxars** [comment]
Well that was embarrassing. I thought I fixed that. For now, lock at 2.2.0, and I'll try to get a new version out with this fixed ASAP.

**Comment by rexxars** [comment]
Ah, so since `commonmark` is still in the 0.x ranges, semver works differently. I keep forgetting that. I just published a new version of `react-markdown` which updates the version ranges for both dependencies, which should fix this. Let me know if I had yet another oversight here somewhere.

**Comment by mooncakelmn** [comment]
Thanks for the quick response @rexxars

**Comment by rgbkrk** [comment]
Thanks for fixing this up, much headache yesterday.
